### ISSUE TITLE
Errors/warnings when starting server

### ISSUE THREAD

**Issue by JustinHoeky** [BeamPoints/Subnautica-Nitrox-Installer-by-BeamPoints#1]
Using the Epic Games version of the game

[Nitrox] Log level set to ConsoleInfo, ConsoleDebug
[Nitrox] W: Couldn't load serializable attribute for Peeper version
[Nitrox] W: Couldn't load serializable attribute for Peeper version
[Nitrox] I: Could not load world: System.IO.InvalidDataException: Persisted state is not valid
   at NitroxServer.Serialization.World.WorldPersistence.LoadFromFile() in C:\Users\patri\OneDrive\Desktop\Nitrox-master\NitroxServer\Serialization\World\WorldPersistence.cs:line 68 creating a new one.
[Nitrox] D: Event Triggerer started!
[Nitrox] W: Couldn't load serializable attribute for Peeper version
[Nitrox] W: Couldn't load serializable attribute for Peeper version
[Nitrox] I: Nitrox Server Started
[Nitrox] I: Saving world state.
[Nitrox] I: World state saved.

![capture2](https://user-images.githubusercontent.com/38039175/50237722-e22fda80-03bd-11e9-8674-e73de2f46b7f.PNG)

**Comment by BeamPoints** [comment]
ok i fix it

**Comment by BeamPoints** [comment]
did you specify the path of the game during the server installation?
